#!/usr/bin/env bash
#
# One way sync: local working copy -> build host.
#
# Why this exists:
#   Rust and Anchor builds run on the host because the toolchain lives there.
#   Editing happens locally because the tooling is faster. Working documentation
#   is gitignored, so git alone cannot carry the full working tree across.
#
# Behaviour:
#   Copies the tree over SSH using tar, then removes files the host still has
#   and the local tree no longer does.
#
#   That second step was added after a rename left a stale file behind. The host
#   kept compiling a module that had been deleted locally, which failed with an
#   error about a dependency that had nothing to do with the real problem. A
#   mirror that only ever adds is not a mirror, and the confusion it causes
#   arrives long after the change that caused it.
#
#   Deletion is confined to paths the sync itself owns. Build output, node
#   modules and anything else excluded below is never considered, because the
#   host is entitled to have those and the local machine may not.
#
# Usage:
#   bash scripts/sync-to-host.sh          sync, then prune
#   bash scripts/sync-to-host.sh --keep   sync only, prune nothing
#
set -euo pipefail

HOST="${CONDUIT_HOST:-root@173.212.238.167}"
DEST="${CONDUIT_DEST:-/root/Stocklana}"
PRUNE=1
[ "${1:-}" = "--keep" ] && PRUNE=0

# Directories that must never cross the wire: they are large, machine specific,
# or regenerated by the build on whichever side needs them.
# Note: .git IS included. Commits only ever happen on the local machine, so the
# host is a faithful mirror. Excluding it would leave the host showing phantom
# uncommitted changes against a stale history.
EXCLUDES=(
  --exclude='./app/node_modules'
  --exclude='./app/.next'
  --exclude='./node_modules'
  --exclude='./target'
  --exclude='./programs/*/target'
  --exclude='./.anchor'
  --exclude='./test-ledger'
)

# The same set, as prune paths. Anything under these is the host's own business.
PRUNE_SKIP="./app/node_modules ./app/.next ./node_modules ./target ./.anchor ./test-ledger ./.test-build"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

echo "syncing $(pwd)"
echo "     -> ${HOST}:${DEST}"

SIZE="$(tar czf - "${EXCLUDES[@]}" . 2>/dev/null | wc -c)"
echo "payload: $((SIZE / 1024)) KB compressed"

tar czf - "${EXCLUDES[@]}" . \
  | ssh -o BatchMode=yes -o ConnectTimeout=20 "$HOST" \
      "mkdir -p '${DEST}' && tar xzf - -C '${DEST}' && echo 'extracted OK'"

if [ "$PRUNE" = "0" ]; then
  echo "sync complete, pruning skipped"
  exit 0
fi

# The manifest is the authority on what should exist. Everything the host has
# under a synced path and the manifest does not name is stale by definition.
MANIFEST="$(tar tzf - < <(tar czf - "${EXCLUDES[@]}" .) 2>/dev/null | grep -v '/$' || true)"

printf '%s\n' "$MANIFEST" \
  | ssh -o BatchMode=yes -o ConnectTimeout=20 "$HOST" "
      set -eu
      cd '${DEST}'
      cat > /tmp/conduit-manifest.txt

      pruned=0
      while IFS= read -r found; do
        skip=0
        for prefix in ${PRUNE_SKIP}; do
          case \"\$found\" in \"\$prefix\"/*) skip=1; break;; esac
        done
        [ \"\$skip\" = 1 ] && continue

        if ! grep -Fxq \"\$found\" /tmp/conduit-manifest.txt; then
          rm -f -- \"\$found\"
          echo \"  pruned \$found\"
          pruned=\$((pruned + 1))
        fi
      done < <(find . -type f)

      rm -f /tmp/conduit-manifest.txt
      find . -type d -empty -not -path './.git/*' -delete 2>/dev/null || true
      echo \"pruned \$pruned stale file(s)\"
    "

echo "sync complete"
