#!/usr/bin/env bash
#
# One way sync: local working copy -> build host.
#
# Why this exists:
#   Rust and Anchor builds run on the host because the toolchain lives there.
#   Editing happens locally because the tooling is faster. Working documentation
#   is gitignored, so git alone cannot carry the full working tree across.
#
# Behaviour:
#   Copies the tree over SSH using tar. Files present on the host but absent
#   locally are NOT deleted, so host only build output survives untouched.
#
# Usage:
#   bash scripts/sync-to-host.sh
#
set -euo pipefail

HOST="${CONDUIT_HOST:-root@173.212.238.167}"
DEST="${CONDUIT_DEST:-/root/Stocklana}"

# Directories that must never cross the wire: they are large, machine specific,
# or regenerated by the build on whichever side needs them.
# Note: .git IS included. Commits only ever happen on the local machine, so the
# host is a faithful mirror. Excluding it would leave the host showing phantom
# uncommitted changes against a stale history.
EXCLUDES=(
  --exclude='./app/node_modules'
  --exclude='./app/.next'
  --exclude='./node_modules'
  --exclude='./target'
  --exclude='./programs/*/target'
  --exclude='./.anchor'
  --exclude='./test-ledger'
)

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

echo "syncing $(pwd)"
echo "     -> ${HOST}:${DEST}"

SIZE="$(tar czf - "${EXCLUDES[@]}" . 2>/dev/null | wc -c)"
echo "payload: $((SIZE / 1024)) KB compressed"

tar czf - "${EXCLUDES[@]}" . \
  | ssh -o BatchMode=yes -o ConnectTimeout=20 "$HOST" \
      "mkdir -p '${DEST}' && tar xzf - -C '${DEST}' && echo 'extracted OK'"

echo "sync complete"
